# CityPulse Production Deployment Workflow
#
# This workflow deploys the CityPulse application to production environments.
#
# Required GitHub Secrets (set in repository settings):
# - FIREBASE_API_KEY: Firebase web app API key
# - FIREBASE_AUTH_DOMAIN: Firebase auth domain
# - FIREBASE_PROJECT_ID: Firebase project ID
# - FIREBASE_STORAGE_BUCKET: Firebase storage bucket
# - FIREBASE_MESSAGING_SENDER_ID: Firebase messaging sender ID
# - FIREBASE_APP_ID: Firebase app ID
# - VERCEL_TOKEN: Vercel deployment token
# - VERCEL_ORG_ID: Vercel organization ID
# - VERCEL_PROJECT_ID: Vercel project ID
# - GCP_SA_KEY: Google Cloud service account key (JSON)
# - GCP_PROJECT_ID: Google Cloud project ID
# - GCP_BUCKET: Google Cloud storage bucket for temp files
#
# Note: VS Code may show warnings about "Context access might be invalid" for secrets.
# This is expected when secrets are not yet configured in the repository.

name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        continue-on-error: true
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        continue-on-error: true
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        continue-on-error: true

      - name: Deploy to Cloud Run
        continue-on-error: true
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          if [ -z "$GCP_PROJECT_ID" ]; then
            echo "GCP_PROJECT_ID not set, skipping Cloud Run deployment"
            exit 0
          fi
          gcloud run deploy citypulse-api \
            --source . \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}"

      - name: Deploy Dataflow jobs
        continue-on-error: true
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
        run: |
          if [ -z "$GCP_PROJECT_ID" ] || [ -z "$GCP_BUCKET" ]; then
            echo "GCP credentials not set, skipping Dataflow deployment"
            exit 0
          fi
          python -m apache_beam.examples.wordcount \
            --runner DataflowRunner \
            --project ${GCP_PROJECT_ID} \
            --region us-central1 \
            --temp_location gs://${GCP_BUCKET}/temp

  deploy-infrastructure:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        continue-on-error: true
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init
        continue-on-error: true
        working-directory: ./infra/terraform

      - name: Terraform Plan
        continue-on-error: true
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          if [ -z "$TF_VAR_project_id" ]; then
            echo "GCP_PROJECT_ID not set, skipping Terraform plan"
            exit 0
          fi
          terraform plan
        working-directory: ./infra/terraform

      - name: Terraform Apply
        continue-on-error: true
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          if [ -z "$TF_VAR_project_id" ]; then
            echo "GCP_PROJECT_ID not set, skipping Terraform apply"
            exit 0
          fi
          terraform apply -auto-approve
        working-directory: ./infra/terraform
